### ISSUE TITLE
Stack recursion depth exceeded 

### ISSUE THREAD

**Issue by DeadP4xel** [FreeMoveProject/dp_mobility_report#72]
Hallo,

wir arbeiten aktuell an einem studentischen Forschungsprojekt, das sich ebenfalls mit der Anonymisierung von Mobilitätsdaten befasst und sind dabei auf Ihre Arbeit und dieses Repository gestoßen. Um uns mit dem DP Mobility Report vertraut zu machen, wollten wir die Library mit eigenen Daten testen, haben dabei aber jedoch jedes Mal denselben Fehler (siehe unten) erhalten. Lediglich mit den von Ihnen hier im Repository zur Verfügung gestellten Testdaten (https://github.com/FreeMoveProject/dp_mobility_report/tree/main/tests/test_files) hat es funktioniert. Wir haben unsere Daten in das gleiche Format gebracht, wie die Testdaten und von Ihnen beschrieben.

Testumgebung:
- Debian 12
- RAM: 32GB CPU: AMD Ryzen 9 7950X
- Conda Environment mit Python 3.10.13
- Panda Version: 1.4.4

Wir erhalten stets folgenden Error-Stack, der durch den Aufruf von self.report in .to_file() und der anschließenden Erzeugung des Singleton entsteht:
```python
   [...] 
    
    Create report:   0%|                                                                                                                                                     Create report:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████Create report:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                            | 3/4 [00:00<00:00,  6.50it/s]
Traceback (most recent call last):
  File "/repo/fp/notebooks/report/test.py", line 17, in <module>
    print(report.report)
  File "/root/anaconda3/envs/fp-report/lib/python3.10/site-packages/dp_mobility_report/dpmreport.py", line 196, in report
    self._report = report.report_elements(self)
  File "/root/anaconda3/envs/fp-report/lib/python3.10/site-packages/dp_mobility_report/report/report.py", line 62, in report_elements
    report = {**report, **add_user_analysis_elements(dpmreport, eps_factor)}
  File "/root/anaconda3/envs/fp-report/lib/python3.10/site-packages/dp_mobility_report/report/report.py", line 235, in add_user_analysis_elements
    ] = user_analysis.get_mobility_entropy(
  File "/root/anaconda3/envs/fp-report/lib/python3.10/site-packages/dp_mobility_report/model/user_analysis.py", line 155, in get_mobility_entropy
    mobility_entropy = _mobility_entropy(dpmreport.df)
  File "/root/anaconda3/envs/fp-report/lib/python3.10/site-packages/dp_mobility_report/model/user_analysis.py", line 146, in _mobility_entropy
    np.divide(entropy, np.log2(n_vals, where=n_vals > 1), where=n_vals > 1),
  File "/root/anaconda3/envs/fp-report/lib/python3.10/site-packages/pandas/core/generic.py", line 2101, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File "/root/anaconda3/envs/fp-report/lib/python3.10/site-packages/pandas/core/arraylike.py", line 397, in array_ufunc
    result = getattr(ufunc, method)(*inputs, **kwargs)

[...]

File "/root/anaconda3/envs/fp-report/lib/python3.10/site-packages/pandas/core/arraylike.py", line 396, in array_ufunc
    inputs = tuple(extract_array(x, extract_numpy=True) for x in inputs)
  File "/root/anaconda3/envs/fp-report/lib/python3.10/site-packages/pandas/core/arraylike.py", line 396, in <genexpr>
    inputs = tuple(extract_array(x, extract_numpy=True) for x in inputs)
  File "/root/anaconda3/envs/fp-report/lib/python3.10/site-packages/pandas/core/construction.py", line 424, in extract_array
    if isinstance(obj, (ABCIndex, ABCSeries)):
RecursionError: maximum recursion depth exceeded

Zudem haben wir folgenden Code zur Erzeugung der Tessellation:
```

```python
import geopandas as gpd
from shapely.geometry import Polygon
from skmob.tessellation import tilers

# INPUT PARAMETERS ################################################
# set boundaries of tessellation in latitude and longitude
MIN_LNG = 116.31
MAX_LNG = 116.39
MIN_LAT = 39.8
MAX_LAT = 40
TILE_DIAMETER_IN_METERS = (
    1000  # approximately. For h3 the most appropriate resolution is found
)
TILE_TYPE = "h3_tessellation"  # other option: "squared"
OUTPUT_PATH = "/repo/fp/notebooks/report/output/tessellation.geojson"
####################################################################


base_shape = gpd.GeoDataFrame(
    index=[0],
    crs=4326,
    geometry=[
        Polygon(
            zip(
                [MIN_LNG, MAX_LNG, MAX_LNG, MIN_LNG],
                [MIN_LAT, MIN_LAT, MAX_LAT, MAX_LAT],
            )
        )
    ],
)

tessellation = tilers.tiler.get(
    TILE_TYPE,
    base_shape=base_shape,
    meters=TILE_DIAMETER_IN_METERS,
)
tessellation.rename(columns={"tile_ID": "tile_id"}, inplace=True)
tessellation.to_file(OUTPUT_PATH)
```

Die Daten, die wir zum Testen verwendet haben, hängen wir an.

Eventuell haben Sie eine Idee, wo unser liegt und können uns weiterhelfen.
 
[testdaten.csv](https://github.com/FreeMoveProject/dp_mobility_report/files/13251954/testdaten.csv)

Vielen Dank vorab für Ihre Mühen!

Viele Grüße

**Comment by AlexandraKapp** [comment]
Hi, 

das Problem scheint bei der *mobility_entropy* aufzutreten, daher würde ich als ersten Quick Fix einmal empfehlen diese Analyse im Report auszuschließen und zu schauen ob der Rest funktioniert...

```
       from dp_mobility_report import constants as const
       report = DpMobilityReport(..., analysis_exclusion=[const.MOBILITY_ENTROPY])
```

Sonst ist mir aufgefallen, dass die Testdaten so aussehen, als wäre pro User (uid) eigentlich nur ein Trip vorhanden, die einzelnen Wegepunkte aber in mehrere Trips (tid) aufgesplittet worden, sodass Quelle-Ziel Paare eigentlich direkt nebeneinander liegen (zeitlich und räumlich). 
Eventuell ist das mit Absicht? Sonst könnte auch die Trip ID (tid) einfach gleich wie die User ID (uid) gesetzt werden. Die Wegepunkte zwischen Quelle und Ziel würden dann im Report ignoriert werden.

Es kann sein, dass das die Ursache für den Fehler ist, wenn jede Quelle-Ziel Verbindung in der gleichen Zelle startet und endet. Das erstmal eine Vermutung, ich werde mir das nächste Woche genauer anschauen - so oder so müsste das natürlich abgefangen werden. :)
Danke auf jeden Fall für den Hinweis!

**Comment by DeadP4xel** [comment]
Vielen Dank für die schnelle und hilfreiche Rückmeldung! Wir konnten nun nach dem Update direkt den Report mit unseren eigentlichen Daten erfolgreich erzeugen (cabspottingdata Datensatz).

Wir hatten nämlich lediglich mit Ihren Example-Daten einen Report erzeugen können, ansonsten jedoch in keiner anderen Konstellation mit anderen Daten. Die Daten, die wir Ihnen letztlich zur Verfügung gestellt hatten, waren letztlich nur ein Resultat verschiedener Modifikationen und Ansätze, um irgendwie einen Report erzeugen zu können und uns auf Fehlersuche zu begeben.

Nochmals danke!
